const data = {
 products:[
     {
         _id : '1',
         name:'Microsoft Surafce Laptop',
         category: 'Laptops',
         image: '/images/p1.jpg',
         price: 80000,
         countInStock: 10,
         brand: 'Microsoft',
         rating: 4.5,
         numReviews: 280,
         description: 'High quality product',
     },
     {
        _id : '2',
        name:'Microsoft Surafce Laptop',
        category: 'Laptops',
        image: '/images/p2.jpg',
        price: 70000,
        countInStock: 10,
        brand: 'Microsoft',
        rating: 3.5,
        numReviews: 190,
        description: 'High quality product',
    },
    {
        _id : '3',
        name:'Lenovo 3EIN slim3',
        category: 'Laptops',
        image: '/images/p3.jpg',
        price: 65000,
        countInStock: 0,
        brand: 'Microsoft',
        rating: 4,
        numReviews: 100,
        description: 'High quality product',
    },
    {
        _id : '4',
        name:'Microsoft Surafce Laptop',
        category: 'Laptops',
        image: '/images/p4.jpg',
        price: 80000,
        countInStock: 10,
        brand: 'Microsoft',
        rating: 5,
        numReviews: 310,
        description: 'High quality product',
    },
    {
        _id : '5',
        name:'Microsoft Surafce Laptop',
        category: 'Laptops',
        image: '/images/p2.jpg',
        price: 80000,
        countInStock: 10,
        brand: 'Microsoft',
        rating: 4.5,
        numReviews: 10,
        description: 'High quality product',
    },
    {
        _id : '6',
        name:'Microsoft Surafce Laptop',
        category: 'Laptops',
        image: '/images/p3.jpg',
        price: 78000,
        countInStock: 10,
        brand: 'Microsoft',
        rating: 5,
        numReviews: 340,
        description: 'High quality product',
    },
    {
        _id : '7',
        name:'Sony Smart TV',
        category: 'TVs',
        image: '/images/t3.jpg',
        price: 18000,
        countInStock: 10,
        brand: 'Sony',
        rating: 5,
        numReviews: 340,
        description: 'High quality product',
    },
 ],
};
export default data;